### The external generator derives from GeneratorPythia8.
[GeneratorExternal]
fileName=${O2DPG_ROOT}/MC/config/PWGGAJE/external/generator/generator_pythia8_gapgenerated_jets.C
funcName=GeneratorPythia8GapGenJE(3)

# [GeneratorPythia8GapTriggeredJetsStandard]
[GeneratorExternal]
config=${O2DPG_ROOT}/MC/config/PWGGAJE/pythia8/generator/pythia8_jet.cfg

# # [GeneratorPythia8MinBias]
# [GeneratorPythia8]
# config=${O2DPG_ROOT}/MC/config/PWGGAJE/pythia8/generator/pythia8_standard.cfg ????????????????????????????

### The external generator derives from GeneratorPythia8.
[GeneratorExternal]
fileName=${O2DPG_ROOT}/MC/config/PWGGAJE/external/generator/generator_pythia8_gaptriggered_jets.C
funcName=GeneratorPythia8GapTriggeredCharmAndBeauty(inputTriggerRatio_thatWeSet)

[GeneratorPythia8]
config=${O2DPG_ROOT}/MC/config/PWGGAJE/pythia8/generator/theConfigWeWroteAbove.cfg